services:
  - type: web
    name: makan-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 20.19.0
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://website-makane.vercel.app
      - key: JWT_SECRET
        value: makan_secure_jwt_secret_dz_2026
      - key: MONGO_URI
        value: mongodb://amany_DB:SkRcN24ncL6vZxz4@ac-bxp3skd-shard-00-00.jmiv0ty.mongodb.net:27017,ac-bxp3skd-shard-00-01.jmiv0ty.mongodb.net:27017,ac-bxp3skd-shard-00-02.jmiv0ty.mongodb.net:27017/makan?ssl=true&authSource=admin&retryWrites=true&w=majority
